module.exports = {
  components: [
    {
      name: "CusImage",
      url: "http://192.168.46.40:8889/resources/CusImage.js",
      sort: 2,
      uuid: 124567321234567,
      setting: {
        src: "https://web-data.zmlearn.com/image/4XxcLWdz7xAjb7JS1jaVH6/banner1.png",
        width: "200",
        height: "200",
        align: "center",
        isJump: false,
        jumpUrl: "",
      },
    },
    {
      name: "CusButton",
      url: "http://192.168.46.40:8889/resources/CusButton.js",
      sort: 1,
      uuid: 9876543456789,
      setting: {
        width: "200",
        height: "40",
        background: "#ff0000",
        borderRadius: "100",
        fontText: "这是一个按钮",
        fontColor: "#ffffff",
        fontWeight: "normal",
        align: "center",
        isJump: false,
        jumpUrl: "",
      },
    },
    {
      name: "CusButton",
      url: "http://192.168.46.40:8889/resources/CusButton.js",
      sort: 11,
      uuid: 9876543456789,
      setting: {
        width: "200",
        height: "40",
        background: "#ff0000",
        borderRadius: "100",
        fontText: "这是一个按钮",
        fontColor: "#ffffff",
        fontWeight: "normal",
        align: "center",
        isJump: false,
        jumpUrl: "",
      },
    },
    {
      name: "CusImage",
      url: "http://192.168.46.40:8889/resources/CusImage.js",
      sort: 21,
      uuid: 124567321234567,
      setting: {
        src: "https://web-data.zmlearn.com/image/4XxcLWdz7xAjb7JS1jaVH6/banner1.png",
        width: "200",
        height: "200",
        align: "center",
        isJump: false,
        jumpUrl: "",
      },
    },
    {
      name: "CusButton",
      url: "http://192.168.46.40:8889/resources/CusButton.js",
      sort: 111,
      uuid: 9876543456789,
      setting: {
        width: "200",
        height: "40",
        background: "#ff0000",
        borderRadius: "100",
        fontText: "这是一个按钮",
        fontColor: "#ffffff",
        fontWeight: "normal",
        align: "center",
        isJump: false,
        jumpUrl: "",
      },
    },
  ],
};
